#!/usr/bin/env bash
# install Nginx where it should be listening on port 80
# and serve a page that would return the str Hello World

echo -e "Updating and installing of Nginx has started.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y
echo -e "\nSetting up minor details.\n"

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart

echo -e "\nDone.\n"
