#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
# Your script should only display:username,user id,
# Home directory path for the user using while loop

while IFS= read -r conts
do
	echo "$conts" | cut -d ":" -f 1,3,6
done < "/etc/passwd"
