#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS.

while IFS= read -r data
do
	user=$(echo "$data" | cut -d ":" -f 1)
	pass=$(echo "$data" | cut -d ":" -f 2)
	uid=$(echo "$data" | cut -d ":" -f 3)
	gid=$(echo "$data" | cut -d ":" -f 4)
	u_info=$(echo "$data" | cut -d ":" -f 5)
	home=$(echo "$data" | cut -d ":" -f 6)
	command=$(echo "$data" | cut -d ":" -f 7)

	echo -n "The user $user is part of the $gid gang. "
	echo -n "lives in $home and rides $command."
	echo -n " $uid's place is protected by the passcode $pass. "
	echo "more info about the user here: $u_info"
done < "/etc/passwd"
