#!/usr/bin/env bash
# a Bash script that displays the content of the current directory
# In a list format where only the part of the name
# after the first dash is displayed 
# using for loop and do not display hidden files

list=$(ls)
for n in $list; do
	echo "$n" | cut -d '-' -f2
done
